name: Python Workspace Testing
on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v3
        with:  # Install Python, skip caching
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: python -m pip install poetry
      - name: Install dependencies
        run: |
          poetry install
      - name: Test with pytest
        run: |
          poetry run pytest



