name: python-workspace docs deployment
on:
  push:
    branches:
      - master
  workflow_call:
jobs:
  deploydocs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install mkdocs
        run: pipx install mkdocs
      - name: Build docs
        run: mkdocs build --clean
      - name: Deploy new docs
        run: mkdocs gh-deploy --force