name: CI
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths: ['python_workspace/**']

jobs:

  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: check_file
      id: check_file_changed
      run : |

        echo "::set-output name=changed_files::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
        echo "::set-output name=doc_diff::$(${{steps.check_file_changed.outputs.all}} | Where-Object { $_ -match '^docs/' -or $_ -match '.md$' })
        # diff=git diff --name-only  origin/master...
        # # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
        # SourceDiff=$diff | Where-Object { $_ -match '^docs/' -or $_ -match '.md$' }
        # HasDiff=$SourceDiff.Length -gt 0

        # # Set the output named "docs_changed"
        # Write-Host "::set-output name=docs_changed::$HasDiff"

    - name: echo_output
      run : |
        echo ${{steps.check_file_changed.outputs.all}}

      # if: steps.check_file_changed.outputs.docs_changed == 'True'
      # run: echo hello
