name: CI
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'python_workspace/**'
      - '!signoff/**'
jobs:
  check-signoff:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - run: exit 1