name: signoff
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'python_workspace/**'
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: ${{ github.ref }}
        filters: |
          signoff-added:
            - 'docs/signoffs/**'
          model-code-changed:
            - 'python_workspace/**.py'
          assumptions-updated:
            - 'python_workspace/inputs/**'
    - name: check-signoff
      if: steps.filter.outputs.signoff-added == 'false'
      run: exit 1
