name: versioner
on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_call:
    inputs:
      version:     
        description: 'Semver type of new version (major / minor / patch)'
        required: true
        type: choice
        options: 
        - patch
        - minor
        - major
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:

    - name: checkout repo
      uses: actions/checkout@v2.4.0

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
        
    - name: setup poetry
      run: |
        python -m pip install -U pip
        pip install poetry 
  
    - name: Setup Git
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@teamname.com"

    - name: bump version
      run: |
        poetry version ${{ github.event.inputs.version }} #the action is not update the code
        git commit -m "bump up ${{ github.event.inputs.version }} version from workflow"
        git push